### ISSUE TITLE
Call CPP SDK from C#

### ISSUE THREAD

**Issue by babaq** [billkarsh/SpikeGLX-CPP-SDK#1]
Hi Bill,

I was thinking about accessing SpikeGLX from C# though the C++ SDK. Our old solution was to warp the MATLAB SDK in .NET Assembly which involved the MATLAB runtime.

The simplest way is to make another C API out of the C++ codebase, since C# could easily p/invoke C DLL library. It should also be useful to other languages, since most of them have a C interface.

There may exist other solutions that can automatically warp C++ Library too.

**Comment by billkarsh** [comment]
See if the newly posted HelloSGLX project on my git helps you. I am aware that other API languages are of interest.

**Comment by babaq** [comment]
Yes, The `HellSGLX` would be able to fulfill most of the slow control purposes.

**Comment by billkarsh** [comment]
Please tell me about what's missing from HelloSGLX. Is there something I could add to that to make it much better for your needs.

**Comment by babaq** [comment]
I have not tried the HelloSGLX, will definitely report any issues later.

**Comment by billkarsh** [comment]
C# is now a fully supported language in the CPP SDK.
