### ISSUE TITLE
example of sglx.c_sglx_getGeomMap in python

### ISSUE THREAD

**Issue by neurochen** [billkarsh/SpikeGLX-CPP-SDK#2]
Hi, I am wondering if you could provide a demo script for getGeomMap in python. It's not intuitive for me using ctypes to read lines from the pointer. Thnaks.

**Comment by billkarsh** [comment]
Usage of c_sglx_getGeomMap would be identical to that for c_sglx_getNIShankMap, which is fully demonstrated in the included file Python/sglx_demo.py.

**Comment by neurochen** [comment]
awesome. worked it out. thanks.
